--
-- PostgreSQL database dump
--

\restrict QGnWseGcqrYHohxENosMQ3qQ69iecYZYjue6wxTf48UZxjspH83NUWDrH3JqcAI

-- Dumped from database version 17.6
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

--
-- Name: update_store_images_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_store_images_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION public.update_store_images_updated_at() OWNER TO postgres;

--
-- Name: update_store_open_hours_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_store_open_hours_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION public.update_store_open_hours_updated_at() OWNER TO postgres;

--
-- Name: update_store_special_open_hours_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_store_special_open_hours_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION public.update_store_special_open_hours_updated_at() OWNER TO postgres;

--
-- Name: update_timestamp(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
  new.updated_at = now();
  return new;
end;
$$;


ALTER FUNCTION public.update_timestamp() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: areas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.areas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    prefecture_id uuid,
    name text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_23ward boolean DEFAULT false,
    display_order integer
);


ALTER TABLE public.areas OWNER TO postgres;

--
-- Name: atmosphere_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.atmosphere_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.atmosphere_definitions OWNER TO postgres;

--
-- Name: baggage_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.baggage_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.baggage_definitions OWNER TO postgres;

--
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    comment text
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.contacts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.contacts OWNER TO postgres;

--
-- Name: customer_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customer_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.customer_definitions OWNER TO postgres;

--
-- Name: drink_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drink_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.drink_definitions OWNER TO postgres;

--
-- Name: environment_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.environment_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.environment_definitions OWNER TO postgres;

--
-- Name: event_trend_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.event_trend_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.event_trend_definitions OWNER TO postgres;

--
-- Name: other_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.other_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.other_definitions OWNER TO postgres;

--
-- Name: payment_method_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_method_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.payment_method_definitions OWNER TO postgres;

--
-- Name: prefectures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prefectures (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    code integer NOT NULL,
    name_ja text NOT NULL,
    name_en text NOT NULL,
    region text
);


ALTER TABLE public.prefectures OWNER TO postgres;

--
-- Name: price_range_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.price_range_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    description text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.price_range_definitions OWNER TO postgres;

--
-- Name: size_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.size_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    capacity_range text,
    description text,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.size_definitions OWNER TO postgres;

--
-- Name: smoking_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.smoking_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.smoking_definitions OWNER TO postgres;

--
-- Name: store_atmospheres; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_atmospheres (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid NOT NULL,
    atmosphere_id uuid NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);


ALTER TABLE public.store_atmospheres OWNER TO postgres;

--
-- Name: store_awards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_awards (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    title text NOT NULL,
    year integer,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_awards OWNER TO postgres;

--
-- Name: store_baggage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_baggage (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    baggage_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_baggage OWNER TO postgres;

--
-- Name: store_customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_customers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    customer_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_customers OWNER TO postgres;

--
-- Name: store_drinks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_drinks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    drink_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_drinks OWNER TO postgres;

--
-- Name: store_environment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_environment (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    environment_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_environment OWNER TO postgres;

--
-- Name: store_event_trends; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_event_trends (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    event_trend_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_event_trends OWNER TO postgres;

--
-- Name: store_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_images (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    image_url text NOT NULL,
    order_num integer DEFAULT 1,
    is_main boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_images OWNER TO postgres;

--
-- Name: store_media_mentions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_media_mentions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    media_name text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    year integer
);


ALTER TABLE public.store_media_mentions OWNER TO postgres;

--
-- Name: store_other; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_other (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    other_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_other OWNER TO postgres;

--
-- Name: store_payment_methods; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_payment_methods (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    payment_method_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_payment_methods OWNER TO postgres;

--
-- Name: store_smoking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_smoking (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    smoking_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_smoking OWNER TO postgres;

--
-- Name: store_toilet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_toilet (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    store_id uuid,
    toilet_id uuid,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.store_toilet OWNER TO postgres;

--
-- Name: store_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_types (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.store_types OWNER TO postgres;

--
-- Name: stores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stores (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    access text,
    address text,
    google_map_url text,
    instagram_url text,
    official_site_url text,
    prefecture_id uuid,
    area_id uuid,
    store_type_id uuid,
    size uuid,
    price_range_id uuid,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    name_kana text,
    x_url text,
    facebook_url text,
    tiktok_url text,
    business_hours text,
    payment_method_other text,
    postcode character varying(8),
    CONSTRAINT area_id_only_for_tokyo CHECK ((((prefecture_id = '9c386ac7-5bb0-4bd4-905d-9c2836fb148f'::uuid) AND (area_id IS NOT NULL)) OR ((prefecture_id <> '9c386ac7-5bb0-4bd4-905d-9c2836fb148f'::uuid) AND (area_id IS NULL))))
);


ALTER TABLE public.stores OWNER TO postgres;

--
-- Name: toilet_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.toilet_definitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    label text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    display_order integer
);


ALTER TABLE public.toilet_definitions OWNER TO postgres;

--
-- Name: areas areas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT areas_pkey PRIMARY KEY (id);


--
-- Name: atmosphere_definitions atmosphere_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atmosphere_definitions
    ADD CONSTRAINT atmosphere_definitions_key_key UNIQUE (key);


--
-- Name: atmosphere_definitions atmosphere_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.atmosphere_definitions
    ADD CONSTRAINT atmosphere_definitions_pkey PRIMARY KEY (id);


--
-- Name: baggage_definitions baggage_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baggage_definitions
    ADD CONSTRAINT baggage_definitions_key_key UNIQUE (key);


--
-- Name: baggage_definitions baggage_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.baggage_definitions
    ADD CONSTRAINT baggage_definitions_pkey PRIMARY KEY (id);


--
-- Name: comments comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- Name: contacts contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.contacts
    ADD CONSTRAINT contacts_pkey PRIMARY KEY (id);


--
-- Name: customer_definitions customer_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_definitions
    ADD CONSTRAINT customer_definitions_key_key UNIQUE (key);


--
-- Name: customer_definitions customer_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customer_definitions
    ADD CONSTRAINT customer_definitions_pkey PRIMARY KEY (id);


--
-- Name: drink_definitions drink_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drink_definitions
    ADD CONSTRAINT drink_definitions_key_key UNIQUE (key);


--
-- Name: drink_definitions drink_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drink_definitions
    ADD CONSTRAINT drink_definitions_pkey PRIMARY KEY (id);


--
-- Name: environment_definitions environment_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environment_definitions
    ADD CONSTRAINT environment_definitions_key_key UNIQUE (key);


--
-- Name: environment_definitions environment_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.environment_definitions
    ADD CONSTRAINT environment_definitions_pkey PRIMARY KEY (id);


--
-- Name: event_trend_definitions event_trend_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_trend_definitions
    ADD CONSTRAINT event_trend_definitions_key_key UNIQUE (key);


--
-- Name: event_trend_definitions event_trend_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.event_trend_definitions
    ADD CONSTRAINT event_trend_definitions_pkey PRIMARY KEY (id);


--
-- Name: other_definitions other_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.other_definitions
    ADD CONSTRAINT other_definitions_key_key UNIQUE (key);


--
-- Name: other_definitions other_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.other_definitions
    ADD CONSTRAINT other_definitions_pkey PRIMARY KEY (id);


--
-- Name: payment_method_definitions payment_method_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_method_definitions
    ADD CONSTRAINT payment_method_definitions_key_key UNIQUE (key);


--
-- Name: payment_method_definitions payment_method_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_method_definitions
    ADD CONSTRAINT payment_method_definitions_pkey PRIMARY KEY (id);


--
-- Name: prefectures prefectures_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prefectures
    ADD CONSTRAINT prefectures_code_key UNIQUE (code);


--
-- Name: prefectures prefectures_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prefectures
    ADD CONSTRAINT prefectures_pkey PRIMARY KEY (id);


--
-- Name: price_range_definitions price_range_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price_range_definitions
    ADD CONSTRAINT price_range_definitions_key_key UNIQUE (key);


--
-- Name: price_range_definitions price_range_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.price_range_definitions
    ADD CONSTRAINT price_range_definitions_pkey PRIMARY KEY (id);


--
-- Name: size_definitions size_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.size_definitions
    ADD CONSTRAINT size_definitions_key_key UNIQUE (key);


--
-- Name: size_definitions size_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.size_definitions
    ADD CONSTRAINT size_definitions_pkey PRIMARY KEY (id);


--
-- Name: smoking_definitions smoking_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.smoking_definitions
    ADD CONSTRAINT smoking_definitions_key_key UNIQUE (key);


--
-- Name: smoking_definitions smoking_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.smoking_definitions
    ADD CONSTRAINT smoking_definitions_pkey PRIMARY KEY (id);


--
-- Name: store_atmospheres store_atmospheres_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_atmospheres
    ADD CONSTRAINT store_atmospheres_pkey PRIMARY KEY (id);


--
-- Name: store_atmospheres store_atmospheres_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_atmospheres
    ADD CONSTRAINT store_atmospheres_unique UNIQUE (store_id, atmosphere_id);


--
-- Name: store_awards store_awards_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_awards
    ADD CONSTRAINT store_awards_pkey PRIMARY KEY (id);


--
-- Name: store_baggage store_baggage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_baggage
    ADD CONSTRAINT store_baggage_pkey PRIMARY KEY (id);


--
-- Name: store_customers store_customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customers
    ADD CONSTRAINT store_customers_pkey PRIMARY KEY (id);


--
-- Name: store_drinks store_drinks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_drinks
    ADD CONSTRAINT store_drinks_pkey PRIMARY KEY (id);


--
-- Name: store_environment store_environment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_environment
    ADD CONSTRAINT store_environment_pkey PRIMARY KEY (id);


--
-- Name: store_event_trends store_event_trends_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_event_trends
    ADD CONSTRAINT store_event_trends_pkey PRIMARY KEY (id);


--
-- Name: store_images store_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_images
    ADD CONSTRAINT store_images_pkey PRIMARY KEY (id);


--
-- Name: store_media_mentions store_media_mentions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_media_mentions
    ADD CONSTRAINT store_media_mentions_pkey PRIMARY KEY (id);


--
-- Name: store_other store_other_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_other
    ADD CONSTRAINT store_other_pkey PRIMARY KEY (id);


--
-- Name: store_payment_methods store_payment_methods_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_payment_methods
    ADD CONSTRAINT store_payment_methods_pkey PRIMARY KEY (id);


--
-- Name: store_smoking store_smoking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_smoking
    ADD CONSTRAINT store_smoking_pkey PRIMARY KEY (id);


--
-- Name: store_toilet store_toilet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_toilet
    ADD CONSTRAINT store_toilet_pkey PRIMARY KEY (id);


--
-- Name: store_types store_types_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_types
    ADD CONSTRAINT store_types_key_key UNIQUE (key);


--
-- Name: store_types store_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_types
    ADD CONSTRAINT store_types_pkey PRIMARY KEY (id);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);


--
-- Name: toilet_definitions toilet_definitions_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.toilet_definitions
    ADD CONSTRAINT toilet_definitions_key_key UNIQUE (key);


--
-- Name: toilet_definitions toilet_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.toilet_definitions
    ADD CONSTRAINT toilet_definitions_pkey PRIMARY KEY (id);


--
-- Name: stores set_stores_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER set_stores_updated_at BEFORE UPDATE ON public.stores FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: store_images update_store_images_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_store_images_updated_at BEFORE UPDATE ON public.store_images FOR EACH ROW EXECUTE FUNCTION public.update_store_images_updated_at();


--
-- Name: areas areas_prefecture_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT areas_prefecture_id_fkey FOREIGN KEY (prefecture_id) REFERENCES public.prefectures(id) ON DELETE CASCADE;


--
-- Name: store_awards fk_store_awards_store; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_awards
    ADD CONSTRAINT fk_store_awards_store FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_event_trends fk_store_event_trends_event; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_event_trends
    ADD CONSTRAINT fk_store_event_trends_event FOREIGN KEY (event_trend_id) REFERENCES public.event_trend_definitions(id) ON DELETE CASCADE;


--
-- Name: store_event_trends fk_store_event_trends_store; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_event_trends
    ADD CONSTRAINT fk_store_event_trends_store FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_media_mentions fk_store_media_store; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_media_mentions
    ADD CONSTRAINT fk_store_media_store FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_atmospheres store_atmospheres_atmosphere_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_atmospheres
    ADD CONSTRAINT store_atmospheres_atmosphere_id_fkey FOREIGN KEY (atmosphere_id) REFERENCES public.atmosphere_definitions(id) ON DELETE CASCADE;


--
-- Name: store_atmospheres store_atmospheres_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_atmospheres
    ADD CONSTRAINT store_atmospheres_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_baggage store_baggage_baggage_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_baggage
    ADD CONSTRAINT store_baggage_baggage_id_fkey FOREIGN KEY (baggage_id) REFERENCES public.baggage_definitions(id) ON DELETE CASCADE;


--
-- Name: store_baggage store_baggage_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_baggage
    ADD CONSTRAINT store_baggage_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_customers store_customers_customer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customers
    ADD CONSTRAINT store_customers_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customer_definitions(id) ON DELETE CASCADE;


--
-- Name: store_customers store_customers_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_customers
    ADD CONSTRAINT store_customers_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_drinks store_drinks_drink_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_drinks
    ADD CONSTRAINT store_drinks_drink_id_fkey FOREIGN KEY (drink_id) REFERENCES public.drink_definitions(id) ON DELETE CASCADE;


--
-- Name: store_drinks store_drinks_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_drinks
    ADD CONSTRAINT store_drinks_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_environment store_environment_environment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_environment
    ADD CONSTRAINT store_environment_environment_id_fkey FOREIGN KEY (environment_id) REFERENCES public.environment_definitions(id) ON DELETE CASCADE;


--
-- Name: store_environment store_environment_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_environment
    ADD CONSTRAINT store_environment_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_images store_images_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_images
    ADD CONSTRAINT store_images_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: store_other store_other_other_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_other
    ADD CONSTRAINT store_other_other_id_fkey FOREIGN KEY (other_id) REFERENCES public.other_definitions(id) ON DELETE CASCADE;


--
-- Name: store_other store_other_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_other
    ADD CONSTRAINT store_other_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_payment_methods store_payment_methods_payment_method_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_payment_methods
    ADD CONSTRAINT store_payment_methods_payment_method_id_fkey FOREIGN KEY (payment_method_id) REFERENCES public.payment_method_definitions(id) ON DELETE CASCADE;


--
-- Name: store_payment_methods store_payment_methods_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_payment_methods
    ADD CONSTRAINT store_payment_methods_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_smoking store_smoking_smoking_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_smoking
    ADD CONSTRAINT store_smoking_smoking_id_fkey FOREIGN KEY (smoking_id) REFERENCES public.smoking_definitions(id) ON DELETE CASCADE;


--
-- Name: store_smoking store_smoking_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_smoking
    ADD CONSTRAINT store_smoking_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_toilet store_toilet_store_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_toilet
    ADD CONSTRAINT store_toilet_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE;


--
-- Name: store_toilet store_toilet_toilet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_toilet
    ADD CONSTRAINT store_toilet_toilet_id_fkey FOREIGN KEY (toilet_id) REFERENCES public.toilet_definitions(id) ON DELETE CASCADE;


--
-- Name: stores stores_area_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id);


--
-- Name: stores stores_prefecture_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_prefecture_id_fkey FOREIGN KEY (prefecture_id) REFERENCES public.prefectures(id);


--
-- Name: stores stores_price_range_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_price_range_id_fkey FOREIGN KEY (price_range_id) REFERENCES public.price_range_definitions(id);


--
-- Name: stores stores_size_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_size_fkey FOREIGN KEY (size) REFERENCES public.size_definitions(id);


--
-- Name: stores stores_store_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stores
    ADD CONSTRAINT stores_store_type_id_fkey FOREIGN KEY (store_type_id) REFERENCES public.store_types(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;


--
-- Name: FUNCTION set_updated_at(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.set_updated_at() TO anon;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;


--
-- Name: FUNCTION update_store_images_updated_at(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.update_store_images_updated_at() TO anon;
GRANT ALL ON FUNCTION public.update_store_images_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.update_store_images_updated_at() TO service_role;


--
-- Name: FUNCTION update_store_open_hours_updated_at(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.update_store_open_hours_updated_at() TO anon;
GRANT ALL ON FUNCTION public.update_store_open_hours_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.update_store_open_hours_updated_at() TO service_role;


--
-- Name: FUNCTION update_store_special_open_hours_updated_at(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.update_store_special_open_hours_updated_at() TO anon;
GRANT ALL ON FUNCTION public.update_store_special_open_hours_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.update_store_special_open_hours_updated_at() TO service_role;


--
-- Name: FUNCTION update_timestamp(); Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON FUNCTION public.update_timestamp() TO anon;
GRANT ALL ON FUNCTION public.update_timestamp() TO authenticated;
GRANT ALL ON FUNCTION public.update_timestamp() TO service_role;


--
-- Name: TABLE areas; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.areas TO anon;
GRANT ALL ON TABLE public.areas TO authenticated;
GRANT ALL ON TABLE public.areas TO service_role;


--
-- Name: TABLE atmosphere_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.atmosphere_definitions TO anon;
GRANT ALL ON TABLE public.atmosphere_definitions TO authenticated;
GRANT ALL ON TABLE public.atmosphere_definitions TO service_role;


--
-- Name: TABLE baggage_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.baggage_definitions TO anon;
GRANT ALL ON TABLE public.baggage_definitions TO authenticated;
GRANT ALL ON TABLE public.baggage_definitions TO service_role;


--
-- Name: TABLE comments; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.comments TO anon;
GRANT ALL ON TABLE public.comments TO authenticated;
GRANT ALL ON TABLE public.comments TO service_role;


--
-- Name: SEQUENCE comment_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.comment_id_seq TO anon;
GRANT ALL ON SEQUENCE public.comment_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.comment_id_seq TO service_role;


--
-- Name: TABLE contacts; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.contacts TO anon;
GRANT ALL ON TABLE public.contacts TO authenticated;
GRANT ALL ON TABLE public.contacts TO service_role;


--
-- Name: TABLE customer_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.customer_definitions TO anon;
GRANT ALL ON TABLE public.customer_definitions TO authenticated;
GRANT ALL ON TABLE public.customer_definitions TO service_role;


--
-- Name: TABLE drink_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.drink_definitions TO anon;
GRANT ALL ON TABLE public.drink_definitions TO authenticated;
GRANT ALL ON TABLE public.drink_definitions TO service_role;


--
-- Name: TABLE environment_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.environment_definitions TO anon;
GRANT ALL ON TABLE public.environment_definitions TO authenticated;
GRANT ALL ON TABLE public.environment_definitions TO service_role;


--
-- Name: TABLE event_trend_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.event_trend_definitions TO anon;
GRANT ALL ON TABLE public.event_trend_definitions TO authenticated;
GRANT ALL ON TABLE public.event_trend_definitions TO service_role;


--
-- Name: TABLE other_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.other_definitions TO anon;
GRANT ALL ON TABLE public.other_definitions TO authenticated;
GRANT ALL ON TABLE public.other_definitions TO service_role;


--
-- Name: TABLE payment_method_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.payment_method_definitions TO anon;
GRANT ALL ON TABLE public.payment_method_definitions TO authenticated;
GRANT ALL ON TABLE public.payment_method_definitions TO service_role;


--
-- Name: TABLE prefectures; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.prefectures TO anon;
GRANT ALL ON TABLE public.prefectures TO authenticated;
GRANT ALL ON TABLE public.prefectures TO service_role;


--
-- Name: TABLE price_range_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.price_range_definitions TO anon;
GRANT ALL ON TABLE public.price_range_definitions TO authenticated;
GRANT ALL ON TABLE public.price_range_definitions TO service_role;


--
-- Name: TABLE size_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.size_definitions TO anon;
GRANT ALL ON TABLE public.size_definitions TO authenticated;
GRANT ALL ON TABLE public.size_definitions TO service_role;


--
-- Name: TABLE smoking_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.smoking_definitions TO anon;
GRANT ALL ON TABLE public.smoking_definitions TO authenticated;
GRANT ALL ON TABLE public.smoking_definitions TO service_role;


--
-- Name: TABLE store_atmospheres; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_atmospheres TO anon;
GRANT ALL ON TABLE public.store_atmospheres TO authenticated;
GRANT ALL ON TABLE public.store_atmospheres TO service_role;


--
-- Name: TABLE store_awards; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_awards TO anon;
GRANT ALL ON TABLE public.store_awards TO authenticated;
GRANT ALL ON TABLE public.store_awards TO service_role;


--
-- Name: TABLE store_baggage; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_baggage TO anon;
GRANT ALL ON TABLE public.store_baggage TO authenticated;
GRANT ALL ON TABLE public.store_baggage TO service_role;


--
-- Name: TABLE store_customers; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_customers TO anon;
GRANT ALL ON TABLE public.store_customers TO authenticated;
GRANT ALL ON TABLE public.store_customers TO service_role;


--
-- Name: TABLE store_drinks; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_drinks TO anon;
GRANT ALL ON TABLE public.store_drinks TO authenticated;
GRANT ALL ON TABLE public.store_drinks TO service_role;


--
-- Name: TABLE store_environment; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_environment TO anon;
GRANT ALL ON TABLE public.store_environment TO authenticated;
GRANT ALL ON TABLE public.store_environment TO service_role;


--
-- Name: TABLE store_event_trends; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_event_trends TO anon;
GRANT ALL ON TABLE public.store_event_trends TO authenticated;
GRANT ALL ON TABLE public.store_event_trends TO service_role;


--
-- Name: TABLE store_images; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_images TO anon;
GRANT ALL ON TABLE public.store_images TO authenticated;
GRANT ALL ON TABLE public.store_images TO service_role;


--
-- Name: TABLE store_media_mentions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_media_mentions TO anon;
GRANT ALL ON TABLE public.store_media_mentions TO authenticated;
GRANT ALL ON TABLE public.store_media_mentions TO service_role;


--
-- Name: TABLE store_other; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_other TO anon;
GRANT ALL ON TABLE public.store_other TO authenticated;
GRANT ALL ON TABLE public.store_other TO service_role;


--
-- Name: TABLE store_payment_methods; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_payment_methods TO anon;
GRANT ALL ON TABLE public.store_payment_methods TO authenticated;
GRANT ALL ON TABLE public.store_payment_methods TO service_role;


--
-- Name: TABLE store_smoking; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_smoking TO anon;
GRANT ALL ON TABLE public.store_smoking TO authenticated;
GRANT ALL ON TABLE public.store_smoking TO service_role;


--
-- Name: TABLE store_toilet; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_toilet TO anon;
GRANT ALL ON TABLE public.store_toilet TO authenticated;
GRANT ALL ON TABLE public.store_toilet TO service_role;


--
-- Name: TABLE store_types; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.store_types TO anon;
GRANT ALL ON TABLE public.store_types TO authenticated;
GRANT ALL ON TABLE public.store_types TO service_role;


--
-- Name: TABLE stores; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.stores TO anon;
GRANT ALL ON TABLE public.stores TO authenticated;
GRANT ALL ON TABLE public.stores TO service_role;


--
-- Name: TABLE toilet_definitions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.toilet_definitions TO anon;
GRANT ALL ON TABLE public.toilet_definitions TO authenticated;
GRANT ALL ON TABLE public.toilet_definitions TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON FUNCTIONS TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA public GRANT ALL ON TABLES TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict QGnWseGcqrYHohxENosMQ3qQ69iecYZYjue6wxTf48UZxjspH83NUWDrH3JqcAI

